# Generated by Django 5.1.4 on 2026-07-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_delete_analysissetting_remove_recommendation_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
